//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define ID_TRANS_CALC                   3
#define IDD_PROGRESS                    103
#define IDC_E_Q                         105
#define IDC_E_DT                        107
#define IDC_E_PAINT                     108
#define IDC_E_WIDTHX                    108
#define IDC_SIZEX                       108
#define IDC_FORCE_K                     109
#define IDC_MD_K                        109
#define IDC_RAND                        110
#define IDC_MD_RAND                     110
#define IDC_E_TIME                      111
#define IDC_EXT_X                       111
#define IDC_EXT_Y                       112
#define IDC_E_SCALE_U                   113
#define IDC_A_DENSITY                   113
#define IDC_A_START                     114
#define IDC_A_STEP_FD                   114
#define CG_IDR_POPUP_FRAME              115
#define IDC_MAX_V                       115
#define IDC_COUNT_X                     116
#define IDC_E_V                         117
#define IDC_RADIUS                      117
#define IDC_MASS                        118
#define IDC_E_PAINT2                    119
#define IDC_DT                          119
#define IDC_STOP                        120
#define IDC_SHOW                        121
#define IDC_SOFT_R                      122
#define IDC_RADIUS_SHOW                 122
#define IDC_LID_V                       123
#define IDC_COUNT_Y                     124
#define IDC_RAND_V                      125
#define IDC_C_X                         126
#define IDC_C_Y                         127
#define IDC_C_RC                        128
#define IDC_C_RA                        129
#define IDC_NAME                        130
#define IDC_FILE                        131
#define IDC_V_MAX_PF                    131
#define IDC_PRINT                       132
#define IDC_SAVE_STEP                   133
#define IDC_C_M                         134
#define IDC_BC_MIRROR_K                 134
#define IDC_C_A0                        135
#define IDC_C_BETA                      136
#define IDC_C_KL                        137
#define IDC_C_KM                        138
#define IDC_C_KP                        139
#define IDC_DPD_SIGMA                   140
#define IDC_T                           141
#define IDC_DPD_RC                      142
#define IDC_DPD_P                       143
#define IDC_DPD_A                       144
#define IDC_C_VISC                      145
#define IDC_C_PARTS                     146
#define IDD_BEGIN_NEW                   147
#define IDC_CPA_T                       147
#define IDD_OPEN                        148
#define IDC_BMP                         148
#define IDC_BMP_STEP                    148
#define IDC_FLOW_UPDATE                 149
#define IDC_A_STEPS                     150
#define IDC_A_STEP_ANL                  150
#define IDC_C_VISC2                     151
#define IDC_C_VISC3                     152
#define IDC_SOFT_R2                     153
#define IDC_PREP_AREA_X                 153
#define IDC_A_STEP_CLOT                 154
#define IDC_FAC_DX                      155
#define IDC_FAC_DT                      156
#define IDC_FAC_ALPHA                   157
#define IDC_FAC_ALPHA1                  157
#define IDC_FAC_ALPHA3                  157
#define IDC_FAC_ALPHA4                  157
#define IDC_FAC_BETA                    158
#define IDC_FAC_W_BEG                   159
#define IDD_TRANS                       160
#define IDC_FAC_W_END                   160
#define IDC_FAC_LEFT                    161
#define IDC_FAC_RIGHT                   162
#define IDC_FAC_TOP                     163
#define IDC_FAC_BOTTOM                  164
#define IDC_FAC_W_END2                  165
#define IDC_FAC_W_VAL                   165
#define IDC_SHOW2                       166
#define IDC_EXC                         166
#define IDC_DT2                         167
#define IDC_FAC_K2A                     168
#define IDC_FAC_ALPHA2                  168
#define IDC_FAC_K2B                     169
#define IDC_FAC_K1                      169
#define IDC_FAC_K3                      170
#define IDC_FAC_K4                      171
#define IDC_FAC_C0                      171
#define IDC_CPP_X                       172
#define IDC_CPP_Y                       173
#define IDC_CPP_ATOM                    174
#define IDC_CPP_A0                      175
#define IDC_CPP_P0                      176
#define IDC_CPP_KL                      177
#define IDC_CPP_KM                      178
#define IDC_CPP_KP                      179
#define IDC_C_PARTS2                    180
#define IDC_CPP_R                       180
#define IDC_CPR_X                       181
#define IDC_CPR_Y                       182
#define IDC_CPR_ATOM                    183
#define IDC_CPR_A0                      184
#define IDC_CPR_P0                      185
#define IDC_CPR_KL                      186
#define IDC_CPR_KM                      187
#define IDC_CPR_KP                      188
#define IDC_CPR_R                       189
#define IDC_FAC_T0                      190
#define IDC_FAC_GAMMA1                  191
#define IDC_FAC_GAMMA2                  191
#define IDC_FAC_GAMMA3                  191
#define IDC_FAC_BETA1                  193
#define IDC_FAC_BETA2                  193
#define IDC_FAC_BETA3                  193
#define IDC_FAC_INIT_FG                 192
#define IDI_ICON                        226
#define IDR_ICON                        226
#define IDD_OPT                         230
#define IDC_CHECK1                      1282
#define IDC_SIZEY                       1406
#define IDC_FORCE_N                     1408
#define IDC_MD_N                        1408
#define IDC_DPD_GAMMA                   1409
#define IDC_START                       1410
#define IDC_SCRIPT                      1411
#define IDC_LOAD                        1412
#define IDC_SAVE                        1413
#define IDC_RESET                       1414
#define IDC_PL_N                        1414
#define IDC_RESUME                      1415
#define IDC_PL_K                        1416
#define IDC_PL_FA                       1416
#define IDC_IMG                         1416
#define IDC_PL_DC                       1417
#define IDC_FLOW_1                      1418
#define IDC_FLOW_3                      1419
#define IDC_FLOW_2                      1420
#define IDC_BC_1                        1421
#define IDC_BC_MIRROR                   1421
#define IDC_BC_2                        1422
#define IDC_BC_SIMPLE                   1422
#define IDC_BC_3                        1423
#define IDC_IMG2                        1423
#define IDC_PARAMS                      1423
#define IDC_MD                          1424
#define IDC_DPD                         1425
#define IDC_G_ALL                       1426
#define IDC_PRESSURE                    1427
#define IDC_IN_RHO                      1427
#define IDC_C_RIGID                     1428
#define IDC_FLOW                        1428
#define IDC_OUT_RHO                     1428
#define IDC_CELL                        1429
#define IDC_IN_D                        1429
#define IDC_ROD                         1430
#define IDC_OUT_D                       1430
#define IDC_RIGID                       1431
#define IDC_IN_U                        1431
#define IDC_CPA                         1432
#define IDC_OUT_U                       1432
#define IDC_C_INSIDE                    1433
#define IDC_IN_N                        1433
#define IDC_IN_NY                       1433
#define IDC_FLOW_NORM                   1434
#define IDC_OUT_N                       1434
#define IDC_MIX                         1435
#define IDC_IN_M                        1435
#define IDC_BC_4                        1436
#define IDC_IN_G                        1436
#define IDC_FIXV                        1437
#define IDC_OUT_M                       1437
#define IDC_FIXV2                       1438
#define IDC_VERLET                      1438
#define IDC_OUT_G                       1438
#define IDC_FM                          1439
#define IDC_PL_ENABLED                  1439
#define IDC_FM_MILI                     1440
#define IDC_PL_VC                       1440
#define IDC_FM_CENTI                    1441
#define IDC_PL_DD                       1441
#define IDC_FM_MICRO                    1442
#define IDC_PL_FIXED                    1442
#define IDC_FM_NANO                     1443
#define IDC_PL_FIX_N                    1443
#define IDC_FM_PICO                     1444
#define IDC_PL_FIX_X                    1444
#define IDC_FM_OTHER                    1445
#define IDC_PL_FIX_DX                   1445
#define IDC_FM_OTHER_V                  1446
#define IDC_PL_M                        1446
#define IDC_FG_KILO                     1447
#define IDC_PL_R                        1447
#define IDC_FG                          1448
#define IDC_BC_5                        1448
#define ID_TRANS_TRANS                  1449
#define IDC_PREP_AREA                   1449
#define IDC_FG_MILI                     1450
#define IDC_C_ENABLED                   1450
#define IDC_FG_MICRO                    1451
#define IDC_BCP_1                       1451
#define IDC_FG_NANO                     1452
#define IDC_BCP_2                       1452
#define IDC_FG_PICO                     1453
#define IDC_INIT                        1453
#define IDC_FG_OTHER                    1454
#define IDC_PREP_AREA2                  1454
#define IDC_RUN_LAST                    1454
#define IDC_FG_OTHER_V                  1455
#define IDC_PL_FB                       1455
#define IDC_FS                          1456
#define IDC_PL_FMAX                     1456
#define ID_TRANS_CLOSE                  1457
#define IDC_PL_F_LIN                    1457
#define IDC_FS_MILI                     1458
#define IDC_PL_F_STEP                   1458
#define IDC_FS_MICRO                    1459
#define IDC_PL_FWEAK                    1459
#define IDC_FS_OTHER                    1460
#define IDC_PL_FSTRONG                  1460
#define IDC_FS_OTHER_V                  1461
#define IDC_OPT_THREADS                 1461
#define IDC_PL_FMAX2                    1461
#define IDC_PL_FT                       1461
#define IDC_TM                          1462
#define IDC_PL_INFLOW                   1462
#define IDC_TM_MILI                     1463
#define IDC_BC_6                        1463
#define IDC_PL_FFIB                     1463
#define IDC_TM_CENTI                    1464
#define IDC_FAC_ENABLED                 1464
#define IDC_TM_MICRO                    1465
#define IDC_BC_7                        1465
#define IDC_TM_NANO                     1466
#define IDC_PL_F_HYB                    1466
#define IDC_TM_PICO                     1467
#define IDC_PL_FT2                      1467
#define IDC_PL_U                        1467
#define IDC_TM_OTHER                    1468
#define IDC_SAVE2                       1468
#define IDC_SAVESTP                     1468
#define IDC_TM_OTHER_V                  1469
#define IDC_BC_8                        1469
#define IDC_TG_KILO                     1470
#define IDC_FAC_HYB1                    1470
#define IDC_TG                          1471
#define IDC_FAC_HYB2                    1471
#define IDC_TG_MILI                     1472
#define IDC_OPT_TEXT_SIZE               1472
#define IDC_CP_PLAT                     1472
#define IDC_CPP                         1472
#define IDC_TG_MICRO                    1473
#define ID_OPT_OK                       1473
#define IDC_CP_RBC                      1473
#define IDC_CPR                         1473
#define IDC_TG_NANO                     1474
#define ID_OPT_CANCEL                   1474
#define IDC_TG_PICO                     1475
#define IDC_OPT_TEXT_SPACE              1475
#define IDC_TG_OTHER                    1476
#define IDC_OPT_IMGW                    1476
#define IDC_TG_OTHER_V                  1477
#define IDC_OPT_OUTPUT                  1477
#define IDC_TS                          1478
#define ID_OPT_BROWSE                   1478
#define IDC_TS_MILI                     1479
#define IDC_TS_MICRO                    1480
#define IDC_TS_OTHER                    1481
#define IDC_GROUP_PL                    1481
#define IDC_TS_OTHER_V                  1482
#define IDC_GROUP_PL2                   1482
#define IDC_PROGRESS1                   1482
#define IDC_IN_MU                       1483
#define IDC_GROUP_PL3                   1483
#define IDC_OUT_MU                      1484
#define IDC_GROUP_PL4                   1484
#define ID_TRANS_GET                    1485
#define IDC_PDE_V2                      1485
#define IDC_GROUP_PL5                   1485
#define IDC_OPT_COLPLA                  1485
#define ID_TRANS_SET                    1486
#define IDC_OPT_COLPLT                  1486
#define IDC_IN_L                        1487
#define IDC_OUT_L                       1488
#define IDC_OPT_COLFIB                  1488
#define IDC_IN_R                        1489
#define IDC_OPT_PLA                     1489
#define IDC_OUT_R                       1490
#define IDC_OPT_PLT                     1490
#define IDC_IN_NX                       1491
#define IDC_OPT_FIB                     1491
#define IDC_OPT_COLF1                   1492
#define IDC_OPT_F1                      1493
#define IDC_OPT_COLF2                   1494
#define IDC_OPT_F2                      1495
#define IDC_DESC                        3333
#define IDR_MENU                        13000
#define ID_VIEW_RESET                   32777
#define ID_VIEW_SELECT                  32785
#define ID_VIEW_CONSTRUCTION            32804
#define ID_FILE_REFRESH                 32807
#define ID_SCRIPT                       32815
#define ID_BUTTON32819                  32819
#define ID_TOOLS_OPTIONS                32820
#define ID_FILE_DPD                     32821
#define ID_FILE_PDE                     32822
#define ID_TOOLS_MEASUREMENTUNITS       32823
#define ID_TOOLS_UNITS                  32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        234
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1490
#define _APS_NEXT_SYMED_VALUE           160
#endif
#endif
